# Generated by Django 5.2.2 on 2025-06-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_book_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returnbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(blank=True, null=True)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.member')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.book')),
            ],
        ),
    ]
